import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./gltf-type-helper";
import utgiagvik from "../../assets/3d-assets/utqiagvik.glb";


export default function Utgiagvik ({ ...props }: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(utgiagvik) as GLTFResult;
  const group = React.useRef<THREE.Group>() as React.RefObject<THREE.Group>;

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[180.18, 2.52, 95.89]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh010.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh010_1.geometry}
          material={materials.lamp}
        />
      </group>
      <group position={[37.22, 12, 113.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh032.geometry}
          material={materials.metal_tin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh032_1.geometry}
          material={materials.antena}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh032_2.geometry}
          material={materials["antena.001"]}
        />
      </group>
      <group position={[10.17, 5.3, 82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh065.geometry}
          material={materials.metal_tin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh065_1.geometry}
          material={materials.antena}
        />
      </group>
      <group position={[47.54, 9.34, 81.01]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh037.geometry}
          material={materials.metal_tin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh037_1.geometry}
          material={materials.antena}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh037_2.geometry}
          material={materials["antena.001"]}
        />
      </group>
      <group position={[16.32, 9.15, 93.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh004.geometry}
          material={materials.metal_tin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh004_1.geometry}
          material={materials.antena}
        />
      </group>
      <group position={[-14, 12.22, 82]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh074.geometry}
          material={materials["metal_tin.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh074_1.geometry}
          material={materials["antena.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh074_2.geometry}
          material={materials["antena.002"]}
        />
      </group>
      <group position={[-6, 12.22, 81.72]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh075.geometry}
          material={materials["metal_tin.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh075_1.geometry}
          material={materials["antena.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh075_2.geometry}
          material={materials["antena.004"]}
        />
      </group>
      <group position={[4, 12.22, 81.72]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh076.geometry}
          material={materials["metal_tin.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh076_1.geometry}
          material={materials["antena.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh076_2.geometry}
          material={materials["antena.006"]}
        />
      </group>
      <group position={[14, 12.22, 81.72]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh077.geometry}
          material={materials["metal_tin.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh077_1.geometry}
          material={materials["antena.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh077_2.geometry}
          material={materials["antena.008"]}
        />
      </group>
      <group position={[22, 12.22, 81.72]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh078.geometry}
          material={materials["metal_tin.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh078_1.geometry}
          material={materials["antena.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh078_2.geometry}
          material={materials["antena.010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pipes025001.geometry}
        material={materials.pipes_01}
        position={[14.12, 2.97, 92.01]}
      />
      <group position={[17.33, 8.58, 90.49]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh009.geometry}
          material={materials.roof_win_base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh009_1.geometry}
          material={materials.roof_win_glass}
        />
      </group>
      <group
        position={[-48.73, 8.95, 123.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh047.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh047_1.geometry}
          material={materials.lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh047_2.geometry}
          material={materials.plywood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh047_3.geometry}
          material={materials.plywood02}
        />
      </group>
      <group
        position={[-31.33, 8.95, 123.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh038.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh038_1.geometry}
          material={materials.lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh038_2.geometry}
          material={materials.plywood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh038_3.geometry}
          material={materials.plywood02}
        />
      </group>
      <group
        position={[-14.51, 8.95, 123.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh039.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh039_1.geometry}
          material={materials.lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh039_2.geometry}
          material={materials.plywood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh039_3.geometry}
          material={materials.plywood02}
        />
      </group>
      <group position={[1.11, 8.95, 123.3]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh041.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh041_1.geometry}
          material={materials.lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh041_2.geometry}
          material={materials.plywood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh041_3.geometry}
          material={materials.plywood02}
        />
      </group>
      <group position={[16.88, 8.95, 123.3]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh042.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh042_1.geometry}
          material={materials.lamp}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh042_2.geometry}
          material={materials.plywood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh042_3.geometry}
          material={materials.plywood02}
        />
      </group>
      <group position={[14.28, 2.05, 90.28]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh007.geometry}
          material={materials.pipes_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh007_1.geometry}
          material={materials.pipes_07}
        />
      </group>
      <group position={[31.01, 5.81, 94.61]} scale={[1, 1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh049.geometry}
          material={materials.pipes_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh049_1.geometry}
          material={materials.went_01}
        />
        <group position={[-4.42, 4.69, 0.91]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh058.geometry}
            material={materials.metal_tin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh058_1.geometry}
            material={materials.antena}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipes025.geometry}
          material={materials.pipes_01}
          position={[-6.62, -1.49, -0.28]}
        />
        <group position={[-6.45, -2.41, -2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh051.geometry}
            material={materials.pipes_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh051_1.geometry}
            material={materials.pipes_07}
          />
        </group>
        <group position={[-3.4, 4.12, -1.79]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh066.geometry}
            material={materials.roof_win_base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh066_1.geometry}
            material={materials.roof_win_glass}
          />
        </group>
        <group position={[159.44, -3.24, 3.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh048.geometry}
            material={materials.rust_met}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh048_1.geometry}
            material={materials.lamp}
          />
        </group>
        <group position={[-5.21, 4.11, 2.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh053.geometry}
            material={materials.pipes_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh053_1.geometry}
            material={materials.pipes_05}
          />
        </group>
        <group position={[-6.45, -1.13, 3.47]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh055.geometry}
            material={materials.pipes_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh055_1.geometry}
            material={materials.went_02}
          />
        </group>
        <group position={[101.11, -21.32, 4.21]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh040.geometry}
            material={materials.wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh040_1.geometry}
            material={materials.roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh040_2.geometry}
            material={materials.door}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh040_3.geometry}
            material={materials.wire}
          />
        </group>
      </group>
      <group position={[31.01, 5.81, 94.61]} scale={[1, 1, -1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh011.geometry}
          material={materials.pipes_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh011_1.geometry}
          material={materials.went_01}
        />
      </group>
      <group
        position={[36.64, 5.81, 95.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1, -1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh012.geometry}
          material={materials.pipes_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh012_1.geometry}
          material={materials.went_01}
        />
        <group position={[-4.42, 4.69, 0.91]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh014.geometry}
            material={materials.metal_tin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh014_1.geometry}
            material={materials.antena}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipes025002.geometry}
          material={materials.pipes_01}
          position={[-6.62, -1.49, -0.28]}
        />
        <group position={[-6.45, -2.41, -2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh017.geometry}
            material={materials.pipes_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh017_1.geometry}
            material={materials.pipes_07}
          />
        </group>
        <group position={[-3.4, 4.12, -1.79]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh019.geometry}
            material={materials.roof_win_base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh019_1.geometry}
            material={materials.roof_win_glass}
          />
        </group>
        <group position={[159.44, -3.24, 3.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh020.geometry}
            material={materials.rust_met}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh020_1.geometry}
            material={materials.lamp}
          />
        </group>
        <group position={[-5.21, 4.11, 2.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh015.geometry}
            material={materials.pipes_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh015_1.geometry}
            material={materials.pipes_05}
          />
        </group>
        <group position={[-6.45, -1.13, 3.47]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh013.geometry}
            material={materials.pipes_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh013_1.geometry}
            material={materials.went_02}
          />
        </group>
        <group position={[101.11, -21.32, 4.21]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh018.geometry}
            material={materials.wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh018_1.geometry}
            material={materials.roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh018_2.geometry}
            material={materials.door}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh018_3.geometry}
            material={materials.wire}
          />
        </group>
      </group>
      <group
        position={[8.85, 5.81, 89.57]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1, 1, -1]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh021.geometry}
          material={materials.pipes_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh021_1.geometry}
          material={materials.went_01}
        />
        <group position={[-4.42, 4.69, 0.91]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh024.geometry}
            material={materials.metal_tin}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh024_1.geometry}
            material={materials.antena}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipes025003.geometry}
          material={materials.pipes_01}
          position={[-6.62, -1.49, -0.28]}
        />
        <group position={[-6.45, -2.41, -2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027.geometry}
            material={materials.pipes_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_1.geometry}
            material={materials.pipes_07}
          />
        </group>
        <group position={[-3.4, 4.12, -1.79]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh029.geometry}
            material={materials.roof_win_base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh029_1.geometry}
            material={materials.roof_win_glass}
          />
        </group>
        <group position={[159.44, -3.24, 3.6]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh030.geometry}
            material={materials.rust_met}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh030_1.geometry}
            material={materials.lamp}
          />
        </group>
        <group position={[-5.21, 4.11, 2.42]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh025.geometry}
            material={materials.pipes_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh025_1.geometry}
            material={materials.pipes_05}
          />
        </group>
        <group position={[-6.45, -1.13, 3.47]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh023.geometry}
            material={materials.pipes_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh023_1.geometry}
            material={materials.went_02}
          />
        </group>
        <group position={[101.11, -21.32, 4.21]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028.geometry}
            material={materials.wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_1.geometry}
            material={materials.roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_2.geometry}
            material={materials.door}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_3.geometry}
            material={materials.wire}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.road.geometry}
        material={materials["pipes_05.001"]}
        position={[4.74, 3.5, 99.67]}
        scale={[80, 1, 20]}
      />
      <group position={[-30.66, 8.88, 112.48]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.cap}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.plank_wood}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.rust_met}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials.pipes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials.glass}
        />
      </group>
      <group position={[-29.81, 8.88, 85.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh068.geometry}
          material={materials["cap.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh068_1.geometry}
          material={materials["plank_wood.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh068_2.geometry}
          material={materials["rust_met.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh068_3.geometry}
          material={materials["pipes.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh068_4.geometry}
          material={materials["glass.001"]}
        />
      </group>
      <group position={[-23.4, 8.88, 112.48]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh069.geometry}
          material={materials["cap.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh069_1.geometry}
          material={materials["plank_wood.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh069_2.geometry}
          material={materials["rust_met.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh069_3.geometry}
          material={materials["pipes.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh069_4.geometry}
          material={materials["glass.002"]}
        />
      </group>
      <group position={[-21.02, 8.88, 85.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh070.geometry}
          material={materials["cap.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh070_1.geometry}
          material={materials["plank_wood.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh070_2.geometry}
          material={materials["rust_met.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh070_3.geometry}
          material={materials["pipes.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh070_4.geometry}
          material={materials["glass.003"]}
        />
      </group>
      <group position={[-22.12, 4.75, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh022.geometry}
          material={materials.tanker}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh022_1.geometry}
          material={materials.metal}
        />
      </group>
      <group position={[-13.17, 5, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh079.geometry}
          material={materials["tanker.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh079_1.geometry}
          material={materials["metal.001"]}
        />
      </group>
      <group position={[-9.53, 5, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh080.geometry}
          material={materials["tanker.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh080_1.geometry}
          material={materials["metal.002"]}
        />
      </group>
      <group position={[-5.61, 4.75, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh081.geometry}
          material={materials["tanker.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh081_1.geometry}
          material={materials["metal.003"]}
        />
      </group>
      <group position={[-26.09, 4.75, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh084.geometry}
          material={materials["tanker.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh084_1.geometry}
          material={materials["metal.006"]}
        />
      </group>
      <group position={[-18, 4.75, 101.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh085.geometry}
          material={materials["tanker.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh085_1.geometry}
          material={materials["metal.007"]}
        />
      </group>
      <group position={[15.53, 8.57, 94.7]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005.geometry}
          material={materials.pipes_03}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005_1.geometry}
          material={materials.pipes_05}
        />
      </group>
      <group position={[14.08, 4.32, 92.99]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002.geometry}
          material={materials.pipes_01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh002_1.geometry}
          material={materials.went_02}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Utqiagvik_2022_Terrain.geometry}
        material={materials["Utqiagvik-mat-HDR"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group position={[121.84, -16.86, 96.49]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh008.geometry}
          material={materials.wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh008_1.geometry}
          material={materials.roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh008_2.geometry}
          material={materials.door}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh008_3.geometry}
          material={materials.wire}
        />
      </group>
    </group>
  );
}

useGLTF.preload(utgiagvik);
