/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./gltf-type-helper";
import waipio from "../../assets/3d-assets/waipio.glb"

export default function Waipio ({ ...props }: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(waipio) as GLTFResult;
  return (
  <group {...props} dispose={null}>
    <group position={[-19.18, 3.35, 14.8]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass1002_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[37.16, 2.08, 50.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass2002_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[29.34, 1.92, 50.54]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass3002_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[31.34, 2.26, 48.97]}
        scale={4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass4003_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[31.58, 1.71, 50.63]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass4004_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[30.76, 1.65, 50.83]}
        scale={3.9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass5002_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[31.56, 2, 52.56]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass6005_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[32.4, 1.7, 51.43]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass6006_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[33.63, 1.63, 50.86]}
        scale={3.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass6007_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[34.57, 1.54, 52.12]}
        scale={5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass6008_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[35.8, 1.7, 51.04]}
        scale={3.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Grass7002_1.geometry}
        material={materials["Grass1_1.005"]}
        position={[38.7, 1.72, 50.92]}
      />
    </group>
    <group position={[34.68, 3.61, 47.2]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh501.geometry}
        material={materials["Tree5_1.010"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh501_1.geometry}
        material={materials["Tree5_2.010"]}
      />
    </group>
    <group position={[0, 3.46, 50.92]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh502.geometry}
        material={materials["Tree1_1.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh502_1.geometry}
        material={materials["Tree1_2.005"]}
      />
    </group>
    <group
      position={[-28.68, 3.6, 53.73]}
      rotation={[Math.PI, -0.94, Math.PI]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh499.geometry}
        material={materials["Tree5_1.009"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh499_1.geometry}
        material={materials["Tree5_2.009"]}
      />
    </group>
    <group
      position={[5.09, 3.57, 43.17]}
      rotation={[-Math.PI / 2, 0, -1.23]}
      scale={100}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh684.geometry}
        material={materials["Stump1_1.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh684_1.geometry}
        material={materials["Stump1_2.006"]}
      />
    </group>
    <group
      position={[-13.49, 3.66, 55.96]}
      rotation={[-Math.PI, 0.36, -Math.PI]}
      scale={0.67}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh154.geometry}
        material={materials["Tree5_1.009"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh154_1.geometry}
        material={materials["Tree5_2.009"]}
      />
    </group>
    <group
      position={[-0.13, 3.49, 78.87]}
      rotation={[-Math.PI, 1.44, -Math.PI]}
      scale={1.69}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh155.geometry}
        material={materials["Tree1_1.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh155_1.geometry}
        material={materials["Tree1_2.005"]}
      />
    </group>
    <group position={[22.4, 3.61, 61.11]} rotation={[0, 1.5, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh156.geometry}
        material={materials["Tree5_1.010"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh156_1.geometry}
        material={materials["Tree5_2.010"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass1001.geometry}
      material={materials["Grass1_1.005"]}
      position={[10.32, 4.86, 63.44]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass2001.geometry}
      material={materials["Grass1_1.005"]}
      position={[2.5, 5.62, 67.51]}
      scale={4}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass3001.geometry}
      material={materials["Grass1_1.005"]}
      position={[4.5, 5.96, 65.94]}
      scale={4}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass4001.geometry}
      material={materials["Grass1_1.005"]}
      position={[4.74, 5.42, 67.6]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass4002.geometry}
      material={materials["Grass1_1.005"]}
      position={[3.92, 5.35, 67.79]}
      scale={3.9}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass5001.geometry}
      material={materials["Grass1_1.005"]}
      position={[4.72, 5.71, 69.53]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6001.geometry}
      material={materials["Grass1_1.005"]}
      position={[5.56, 5.41, 68.4]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6002.geometry}
      material={materials["Grass1_1.005"]}
      position={[6.79, 5.34, 67.83]}
      scale={3.35}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6003.geometry}
      material={materials["Grass1_1.005"]}
      position={[7.72, 5.25, 69.09]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6004.geometry}
      material={materials["Grass1_1.005"]}
      position={[8.96, 5.41, 68.01]}
      scale={3.41}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass7001.geometry}
      material={materials["Grass1_1.005"]}
      position={[11.86, 5.43, 67.88]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass1002.geometry}
      material={materials["Grass1_1.005"]}
      position={[37.16, 2.08, 50.39]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass2002.geometry}
      material={materials["Grass1_1.005"]}
      position={[29.34, 1.92, 50.54]}
      scale={4}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass3002.geometry}
      material={materials["Grass1_1.005"]}
      position={[31.34, 2.26, 48.97]}
      scale={4}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass4003.geometry}
      material={materials["Grass1_1.005"]}
      position={[31.58, 1.71, 50.63]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass4004.geometry}
      material={materials["Grass1_1.005"]}
      position={[30.76, 1.65, 50.83]}
      scale={3.9}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass5002.geometry}
      material={materials["Grass1_1.005"]}
      position={[31.56, 2, 52.56]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6005.geometry}
      material={materials["Grass1_1.005"]}
      position={[32.4, 1.7, 51.43]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6006.geometry}
      material={materials["Grass1_1.005"]}
      position={[33.63, 1.63, 50.86]}
      scale={3.35}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6007.geometry}
      material={materials["Grass1_1.005"]}
      position={[34.57, 1.54, 52.12]}
      scale={5}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass6008.geometry}
      material={materials["Grass1_1.005"]}
      position={[35.8, 1.7, 51.04]}
      scale={3.41}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Grass7002.geometry}
      material={materials["Grass1_1.005"]}
      position={[38.7, 1.72, 50.92]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big.geometry}
      material={materials.cartoon_cliffs}
      position={[-97.91, 16.09, -20.36]}
      rotation={[0, 0.45, 0]}
      scale={0.04}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3001.geometry}
      material={materials.cartoon_cliffs}
      position={[23.47, 2.64, -0.47]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1001.geometry}
      material={materials.cartoon_cliffs}
      position={[12.14, 3.23, 12.98]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock3001.geometry}
      material={materials.cartoon_cliffs}
      position={[13.61, 3.25, 13]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock4001.geometry}
      material={materials.cartoon_cliffs}
      position={[15.51, 3.22, 13.19]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5001.geometry}
      material={materials.cartoon_cliffs}
      position={[17.52, 3.26, 12.76]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Ice_Colision_Middle_Snow.geometry}
      material={materials.cartoon_cliffs}
      position={[80.35, -0.16, -27.59]}
      rotation={[-Math.PI, 0.71, -Math.PI]}
      scale={0.17}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock2001.geometry}
      material={materials.cartoon_cliffs}
      position={[10.65, 3.39, 12.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow.geometry}
      material={materials.cartoon_cliffs}
      position={[-63.25, 3.14, 18.01]}
      scale={0.01}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow002.geometry}
      material={materials.cartoon_cliffs}
      position={[-65.43, 2.32, -1.38]}
      rotation={[-Math.PI, 0.64, -Math.PI]}
      scale={0.01}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow004.geometry}
      material={materials.cartoon_cliffs}
      position={[-72.53, 1.42, -11.73]}
      scale={0.02}
    />
    <group position={[1.67, 2.9, 51.03]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh510.geometry}
        material={materials.cartoon_cliffs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh510_1.geometry}
        material={materials["Flower3_3.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh510_2.geometry}
        material={materials["Flower3_1.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh510_3.geometry}
        material={materials["Flower3_2.004"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh510_4.geometry}
        material={materials["Grass1_1.005"]}
      />
    </group>
    <group position={[0, 3.12, 49.47]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511.geometry}
        material={materials.cartoon_cliffs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_1.geometry}
        material={materials["Mushroom1_1.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_2.geometry}
        material={materials["Mushroom1_2.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_3.geometry}
        material={materials["Flower1_1.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_4.geometry}
        material={materials["Flower1_2.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_5.geometry}
        material={materials["Flower1_3.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh511_6.geometry}
        material={materials["Grass1_1.005"]}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Ice_Colision_Middle_Snow001.geometry}
      material={materials.cartoon_cliffs}
      position={[69.87, -0.79, -11.89]}
      rotation={[0, 1.19, 0]}
      scale={0.37}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow001.geometry}
      material={materials.cartoon_cliffs}
      position={[15.07, 3.47, 71.72]}
      scale={0.03}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow006.geometry}
      material={materials.cartoon_cliffs}
      position={[-24.92, 3.64, 63.71]}
      scale={0.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow007.geometry}
      material={materials.cartoon_cliffs}
      position={[-58.94, 3.4, 10.62]}
      rotation={[-Math.PI, 0.64, -Math.PI]}
      scale={0.01}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow008.geometry}
      material={materials.cartoon_cliffs}
      position={[-60.64, 3.15, 51.33]}
      rotation={[-Math.PI, 1.39, -Math.PI]}
      scale={0.04}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5002.geometry}
      material={materials.cartoon_cliffs}
      position={[35.81, 3.26, 14.03]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5003.geometry}
      material={materials.cartoon_cliffs}
      position={[-57.57, 1.6, -14.24]}
      rotation={[-Math.PI / 2, 0, 0.56]}
      scale={187.9}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5004.geometry}
      material={materials.cartoon_cliffs}
      position={[-37.15, 3.26, 12.96]}
      rotation={[-Math.PI / 2, 0, 2.51]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5005.geometry}
      material={materials.cartoon_cliffs}
      position={[-47.64, 3.26, 18.25]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5006.geometry}
      material={materials.cartoon_cliffs}
      position={[-27.43, 3.26, 14.7]}
      rotation={[-Math.PI / 2, 0, 1.05]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1002.geometry}
      material={materials.cartoon_cliffs}
      position={[-35.42, 3.7, 23.84]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1003.geometry}
      material={materials.cartoon_cliffs}
      position={[-34.58, 3.7, 24.93]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1004.geometry}
      material={materials.cartoon_cliffs}
      position={[-33.07, 3.7, 25.29]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1005.geometry}
      material={materials.cartoon_cliffs}
      position={[-33.67, 3.7, 27.95]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1006.geometry}
      material={materials.cartoon_cliffs}
      position={[-30.41, 3.7, 28.49]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1007.geometry}
      material={materials.cartoon_cliffs}
      position={[-28.36, 3.7, 27.52]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1008.geometry}
      material={materials.cartoon_cliffs}
      position={[-33.25, 3.7, 31.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1009.geometry}
      material={materials.cartoon_cliffs}
      position={[-30.84, 3.7, 32.29]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1010.geometry}
      material={materials.cartoon_cliffs}
      position={[-29.09, 3.7, 31.27]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1011.geometry}
      material={materials.cartoon_cliffs}
      position={[-26.67, 3.7, 28.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1012.geometry}
      material={materials.cartoon_cliffs}
      position={[-19.77, 3.7, 28.58]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1013.geometry}
      material={materials.cartoon_cliffs}
      position={[-19.02, 3.7, 28.06]}
      rotation={[-Math.PI / 2, 0, -2.48]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1014.geometry}
      material={materials.cartoon_cliffs}
      position={[-18.82, 3.7, 28.81]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1015.geometry}
      material={materials.cartoon_cliffs}
      position={[-12.93, 3.92, 28.54]}
      rotation={[-Math.PI / 2, 0, 1.46]}
      scale={54.89}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1016.geometry}
      material={materials.cartoon_cliffs}
      position={[-12.96, 3.75, 26.76]}
      rotation={[-Math.PI / 2, 0, 1.92]}
      scale={188.17}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1017.geometry}
      material={materials.cartoon_cliffs}
      position={[-14.8, 3.77, 25.35]}
      rotation={[-Math.PI / 2, 0, -1.48]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1018.geometry}
      material={materials.cartoon_cliffs}
      position={[-12.19, 3.72, 25.17]}
      rotation={[-Math.PI / 2, 0, 0.64]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1019.geometry}
      material={materials.cartoon_cliffs}
      position={[-7.84, 3.7, 29.76]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1020.geometry}
      material={materials.cartoon_cliffs}
      position={[-25.89, 3.23, 7.36]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5007.geometry}
      material={materials.cartoon_cliffs}
      position={[-28.54, 3.26, 7.39]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5008.geometry}
      material={materials.cartoon_cliffs}
      position={[-28.66, 3.26, 16.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3002.geometry}
      material={materials.cartoon_cliffs}
      position={[-65.49, 2.98, -20.85]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3003.geometry}
      material={materials.cartoon_cliffs}
      position={[-38.94, 1.58, 11.95]}
      rotation={[-Math.PI / 2, 0, 2.03]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3004.geometry}
      material={materials.cartoon_cliffs}
      position={[28.13, 2.98, 22.34]}
      rotation={[-Math.PI / 2, 0, -2.78]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3005.geometry}
      material={materials.cartoon_cliffs}
      position={[-27.68, 1, -12.34]}
      rotation={[-Math.PI / 2, 0, -0.03]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3006.geometry}
      material={materials.cartoon_cliffs}
      position={[-50.27, 2.67, 22.14]}
      rotation={[-Math.PI / 2, 0, 1.91]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow009.geometry}
      material={materials.cartoon_cliffs}
      position={[40.18, 3.23, 9.75]}
      rotation={[-Math.PI, 0.36, -Math.PI]}
      scale={0.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5009.geometry}
      material={materials.cartoon_cliffs}
      position={[18.79, 2.52, 11.07]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5010.geometry}
      material={materials.cartoon_cliffs}
      position={[23.62, 2.52, 8.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5011.geometry}
      material={materials.cartoon_cliffs}
      position={[33.46, 1.4, -0.64]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5012.geometry}
      material={materials.cartoon_cliffs}
      position={[34.54, 1.55, -2.25]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={105.26}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5013.geometry}
      material={materials.cartoon_cliffs}
      position={[-35.96, 3.26, 8.65]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5014.geometry}
      material={materials.cartoon_cliffs}
      position={[-34.39, 3.26, 13.48]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5015.geometry}
      material={materials.cartoon_cliffs}
      position={[-37.41, 3.26, 20.47]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5016.geometry}
      material={materials.cartoon_cliffs}
      position={[-62.35, 3.26, -19.98]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5017.geometry}
      material={materials.cartoon_cliffs}
      position={[-57.48, 3.26, -20.15]}
      rotation={[-Math.PI / 2, 0, 1.45]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5018.geometry}
      material={materials.cartoon_cliffs}
      position={[-62.6, 3.26, -17.88]}
      rotation={[-Math.PI / 2, 0, -1.21]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5019.geometry}
      material={materials.cartoon_cliffs}
      position={[-63.98, 3.26, -17.02]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5020.geometry}
      material={materials.cartoon_cliffs}
      position={[-40.8, 2.13, 8.79]}
      rotation={[-Math.PI / 2, 0, -2.72]}
      scale={187.9}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1021.geometry}
      material={materials.cartoon_cliffs}
      position={[32.79, 3.23, -2.3]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1022.geometry}
      material={materials.cartoon_cliffs}
      position={[31.88, 3.23, -1.39]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1023.geometry}
      material={materials.cartoon_cliffs}
      position={[31.58, 3.23, -2.3]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1024.geometry}
      material={materials.cartoon_cliffs}
      position={[30.8, 3.23, -3.2]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1025.geometry}
      material={materials.cartoon_cliffs}
      position={[31.82, 3.23, -3.2]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1026.geometry}
      material={materials.cartoon_cliffs}
      position={[31.94, 3.23, -4.23]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1027.geometry}
      material={materials.cartoon_cliffs}
      position={[28.44, 3.23, 1.99]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1028.geometry}
      material={materials.cartoon_cliffs}
      position={[29.17, 3.23, -1.33]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1029.geometry}
      material={materials.cartoon_cliffs}
      position={[27.6, 3.23, -0.24]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1030.geometry}
      material={materials.cartoon_cliffs}
      position={[25.18, 3.23, 1.75]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1031.geometry}
      material={materials.cartoon_cliffs}
      position={[27.17, 3.23, 1.02]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1032.geometry}
      material={materials.cartoon_cliffs}
      position={[26.63, 3.23, 3.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1033.geometry}
      material={materials.cartoon_cliffs}
      position={[25.3, 3.23, 3.2]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock1034.geometry}
      material={materials.cartoon_cliffs}
      position={[25.97, 3.23, 5.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5021.geometry}
      material={materials.cartoon_cliffs}
      position={[30.74, 1.4, -1.18]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5022.geometry}
      material={materials.cartoon_cliffs}
      position={[-36.14, 2.49, 3.51]}
      rotation={[-Math.PI / 2, 0, 1.77]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5023.geometry}
      material={materials.cartoon_cliffs}
      position={[25.37, 3.35, 20.43]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.BigRock3007.geometry}
      material={materials.cartoon_cliffs}
      position={[38.59, 2.59, 41.9]}
      rotation={[-Math.PI / 2, 0, -2.78]}
      scale={95.32}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow010.geometry}
      material={materials.cartoon_cliffs}
      position={[-16.28, 3.62, 78.21]}
      rotation={[0, 1.35, 0]}
      scale={0.03}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow011.geometry}
      material={materials.cartoon_cliffs}
      position={[-4.67, 3.64, 72.19]}
      scale={0.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow012.geometry}
      material={materials.cartoon_cliffs}
      position={[-71.19, 0.72, -30.42]}
      scale={0.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5024.geometry}
      material={materials.cartoon_cliffs}
      position={[-30.4, 1.65, -13.47]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={241.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Rock5025.geometry}
      material={materials.cartoon_cliffs}
      position={[16.84, 3.26, 0.43]}
      rotation={[-Math.PI / 2, 0, 1.45]}
      scale={100}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow013.geometry}
      material={materials.cartoon_cliffs}
      position={[20.5, 0.72, -9.84]}
      scale={0.02}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Ice_Colision_Middle_Snow002.geometry}
      material={materials.cartoon_cliffs}
      position={[52.64, 0.79, -16.41]}
      scale={0.22}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big001.geometry}
      material={materials["cartoon_cliffs.001"]}
      position={[-86.61, 23.67, 18.08]}
      rotation={[0, -1.44, 0]}
      scale={0.05}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big002.geometry}
      material={materials["cartoon_cliffs.001"]}
      position={[-86.78, 61.89, 137.61]}
      rotation={[-Math.PI, 0.73, -Math.PI]}
      scale={0.14}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big003.geometry}
      material={materials["cartoon_cliffs.001"]}
      position={[-269.42, 134.23, -154.16]}
      rotation={[0, -1.53, 0]}
      scale={0.31}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big004.geometry}
      material={materials["cartoon_cliffs.001"]}
      position={[93.91, 38.62, 22.14]}
      rotation={[Math.PI, -1.53, Math.PI]}
      scale={0.09}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Big005.geometry}
      material={materials["cartoon_cliffs.001"]}
      position={[25.7, 38.62, 114.04]}
      rotation={[0, 0.53, 0]}
      scale={0.09}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.TerrainWaipio_2022.geometry}
      material={materials["cartoon_cliffs.003"]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={0.01}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow003.geometry}
      material={materials["cartoon_cliffs.003"]}
      position={[-50.37, 1.46, -9.95]}
      scale={0.01}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Clif_Small_Snow005.geometry}
      material={materials["cartoon_cliffs.003"]}
      position={[-57.52, 2.69, 0.63]}
      scale={0.02}
    />
  </group>
  );
}

useGLTF.preload(waipio);
